### ISSUE TITLE
bot is extracting videos from yt in 640*360 res

### ISSUE THREAD

**Issue by aritradatta0** [eyaadh/megadlbot_oss#36]
If would be great if bot supports 1080p downloading from youtube

**Comment by eyaadh** [comment]
I addressed this on the 16th [video](https://youtu.be/dKvsq0FhW94?t=849) of YouTube series. Have a look, I shared the link with the exact time for the frame where I started talking about it on the video.

However if you still wish to change the quality of the YouTube videos downloaded, you can alter the following [line](https://github.com/eyaadh/megadlbot_oss/blob/448cb686793f4237232f0e4591f9da0ee17f9b2b/mega/helpers/ytdl.py#L46).

_Currently it is:_
`'format': 'bestvideo[height<=480][ext=mp4]+bestaudio[height<=480][ext=m4a]/best',`
_basically what this means is download best format available but not better that 480p. Change it to:_
`'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best',`
_the above amendment will upload the best available quality, however keep in mind **there are limitations to file sizes** which you can upload on telegram. Increase in quality == Increase in file size_ 

That being said, given the complications I discussed on the YouTube video and the above mentioned I do not think this would be a beneficial amendment to do on the main repo i.e. I will close this issue with the hope I have given you a workaround that you can do on your environment to do the necessary amendments to fit your needs.

**Comment by aritradatta0** [comment]
Thank You very Much Sir
