### ISSUE TITLE
Plugins not loading on Heroku

### ISSUE THREAD

**Issue by phoenixatom** [eyaadh/megadlbot_oss#4]
- Deployment is successful, however no plugins are loaded. Below is the heroku log

![image](https://user-images.githubusercontent.com/18140039/93274838-ba5ce900-f7d4-11ea-9327-e95e19d48e64.png)

- Tested with different plugin root directories, both "mega/telegram/plugins" and "telegram/plugins"
- Suggested fix is to change the decorators.

**Comment by eyaadh** [comment]
https://github.com/eyaadh/megadlbot_oss/commit/597744d69be467476ee3860532ab5b0a5b2162d4
This commit should have fixed the issues with loading the plugins can you please reconfirm, I do not have a Heroku instance to check it mate.

**Comment by phoenixatom** [comment]
Tested and works perfectly!
