### ISSUE TITLE
Questions about downloading from googledrive links

### ISSUE THREAD

**Issue by Ranofult** [eyaadh/megadlbot_oss#52]
Hi, the bot doesn't seem to download the content from the GoogleDrive share link correctly, is the bot not supporting this feature or am I using it incorrectly?

**Comment by eyaadh** [comment]
Unfortunately unless you share us a log file or more details on the context with proper errors that we can diagnosis we can't answer a generic "not working".

**Comment by eyaadh** [comment]
I am closing this issue as there has been no reply with the requested logs no any context we can further work with assisting in a resolution to mentioned.
