### ISSUE TITLE
Web Server Heroku

### ISSUE THREAD

**Issue by arjung24** [eyaadh/megadlbot_oss#62]
What will be the web server for heroku deployment

[web_server]
bind_address = ??
fqdn = ??
port = ??

Help is needed! A video guide will help a lot for heroku deployment.
Thanks and love 😍😍

**Comment by eyaadh** [comment]
We had a huge youtube playlist explaining the whole built from scratch
https://youtube.com/playlist?list=PLApP3aDELGhvQqPcA_DsTSt-sA0v2OkqP

I believe the details you are looking for can be found with this video:
https://www.youtube.com/watch?v=ktz0n5vNooQ&list=PLApP3aDELGhvQqPcA_DsTSt-sA0v2OkqP&index=15&t=8s

For heroku it doesn't look for the config.ini file.
